### ISSUE TITLE
Error: Not implemented: isContext

### ISSUE THREAD

**Issue by chrisabrams** [john-griffin/deno-dom-test#1]
Hey @john-griffin thanks for putting this repo together. I tried it out but was unable to get the expected output (test passing). When I run `deno test --allow-env` I get the following error: `Error: Not implemented: isContext`. I have confirmed that the import map is being picked up, so it should be seeing the patched file?

Here's my deno version if that's helpful:

```
deno --version
deno 1.29.1 (release, aarch64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by john-griffin** [comment]
Thanks @chrisabrams. At first I was not able to see this but then I was able to reproduce this by removing the `deno.lock` file and running `deno cache --reload index.t*`. The import map was relying `0.165` of std, which is now at `0.170`. This is fixed in 86f2c7c0620974d840cf4ef58e24afaad091a767.

However this will break again for new users when they bump again. We need to figure out a way to make the import map work with any version of std.
